##########################################
###-----Munge & LDSC for all data-----####
##########################################

#设置环境
#conda activate ldsc

#_____________Munge Data_____________#
###Attention!! Some of the targets are seperated!!!
###Including scz2012,bd2012, mdd2013, scz2014

#For normal traits
cd /exeh_4/jinghong_qiu/SO_Lab/impute/
for i in *.impute.map.txt
do
    outputname=${i%.i*}
    position=$(awk 'BEGIN{ FS=" ";}
    NR == 1 { 
       for (i=1; i <= NF; ++i) {
          if ($i == "n") {
          position=i;
         }
        }
      }
    END{ print position ;}' $y)
    lines=$(awk 'NR!=1{print $var}' var="${position}" $y | head -1 )


    /exeh_3/rstao/programs/ldsc/munge_sumstats.py \
        --sumstats  /exeh_4/jinghong_qiu/SO_Lab/impute/$i  \
        --N   $lines  \
        --out /exeh_4/jinghong_qiu/SO_Lab/Munge_all/$outputname \
        --merge-alleles /exeh_3/rstao/programs/ldsc/w_hm3.snplist

done

#For some targets
cd /exeh_4/jinghong_qiu/SO_Lab/impute/Special_Targets
for i in *.impute.map.txt
do
    outputname=${i%.i*}
	y=$(echo /exeh_3/rstao/dr.so/002.meta/002.clear.data/targets/$outputname'.clear.txt')
    position=$(awk 'BEGIN{ FS=" ";}
    NR == 1 { 
       for (i=1; i <= NF; ++i) {
          if ($i == "n") {
          position=i;
         }
        }
      }
    END{ print position ;}' $y)
    lines=$(awk 'NR!=1{print $var}' var="${position}" $y | head -1 )


    /exeh_3/rstao/programs/ldsc/munge_sumstats.py \
        --sumstats  /exeh_4/jinghong_qiu/SO_Lab/impute/Special_Targets/$i  \
        --N   $lines  \
        --out /exeh_4/jinghong_qiu/SO_Lab/Munge_all/$outputname \
        --merge-alleles /exeh_3/rstao/programs/ldsc/w_hm3.snplist

done


#_____________LDSC_____________#
###Getting the matrix of all data
###Including scz2012,bd2012, mdd2013,scz2014

###__Part_All_1
cd /exeh_4/jinghong_qiu/SO_Lab/Munge_all/

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg ad.sumstats.gz,adhd2019.sumstats.gz,alco2018.sumstats.gz,antisocial.sumstats.gz,anx.sumstats.gz,asd2019.sumstats.gz,bd2018.sumstats.gz,cannabis.sumstats.gz,child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_2.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg adhd2019.sumstats.gz,alco2018.sumstats.gz,antisocial.sumstats.gz,anx.sumstats.gz,asd2019.sumstats.gz,bd2018.sumstats.gz,cannabis.sumstats.gz,child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_3.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg alco2018.sumstats.gz,antisocial.sumstats.gz,anx.sumstats.gz,asd2019.sumstats.gz,bd2018.sumstats.gz,cannabis.sumstats.gz,child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_4.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg antisocial.sumstats.gz,anx.sumstats.gz,asd2019.sumstats.gz,bd2018.sumstats.gz,cannabis.sumstats.gz,child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_5.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg anx.sumstats.gz,asd2019.sumstats.gz,bd2018.sumstats.gz,cannabis.sumstats.gz,child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_6.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg asd2019.sumstats.gz,bd2018.sumstats.gz,cannabis.sumstats.gz,child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_7.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg bd2018.sumstats.gz,cannabis.sumstats.gz,child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_8.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg cannabis.sumstats.gz,child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_9.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg child.iq2014.sumstats.gz,chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_10.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg chrono.sumstats.gz,college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_11.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg college2013.sumstats.gz,dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_12.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg dx.dep.sumstats.gz,dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_13.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg dx.life.threat.ill.sumstats.gz,ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_14.txt 2>&1 &


nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg ed2019.sumstats.gz,edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_15.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg edu.sumstats.gz,ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_16.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg ever.csh.sumstats.gz,ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_17.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg ever.sh.sumstats.gz,ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_18.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg ever.st.sumstats.gz,insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_19.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg insom2019.sumstats.gz,inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_20.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg inte.sumstats.gz,life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_21.txt 2>&1 &


nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg life.threat.accident.sumstats.gz,mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_22.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg mdd2019.sumstats.gz,mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_23.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg mddco.sumstats.gz,neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_24.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg neo.c.sumstats.gz,neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_25.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg neo.o.sumstats.gz,neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_26.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg neuroti2018.sumstats.gz,no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_27.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_28.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg no.dep.sumstats.gz,ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_29.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg ocd2018.sumstats.gz,pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_30.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg pd.sumstats.gz,physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_31.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg physical.crime.sumstats.gz,psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_32.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg psycho.experi.sumstats.gz,ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_33.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg ptsd2019.sumstats.gz,reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_34.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg reac.sumstats.gz,sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_35.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg sa.ipsych.sumstats.gz,scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_36.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg scz.eas2019.sumstats.gz,sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_37.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg sleep.dura.sumstats.gz,smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_38.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg smoking.sumstats.gz,st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_39.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg st.sumstats.gz,st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_40.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg st.dep.sumstats.gz,tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_41.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg tense.sumstats.gz,wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_42.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg wal.scz2018.sumstats.gz,wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_43.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg wit.death.sumstats.gz,scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_44.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg scz2012.sumstats.gz,scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_45.txt 2>&1 &


nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg scz2014.sumstats.gz,bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_46.txt 2>&1 &

nohup /exeh_4/jinghong_qiu/ldsc/ldsc.py --rg bd2012.sumstats.gz,mdd2013.sumstats.gz --ref-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --w-ld-chr /exeh_3/rstao/programs/ldsc/eur_w_ld_chr/ --out /exeh_4/jinghong_qiu/20200403LDSC_ALL_47.txt 2>&1 &