# Project: FDRreg Sensitivity Analysis (SNP + MAGMA + SmultiXcan)
# File: fdrreg_sensitivity_analysis_rg.R
# Description: Comprehensive sensitivity analysis for FDRreg across three levels:
#              1. SNP-level:
#                 Reuses harmonised and, when applicable, decorrelated z-scores
#                 from the MAGMA input files generated by fdrreg.R.
#              2. MAGMA gene-level:
#                 No decorrelation and no biological annotations.
#              3. SmultiXcan gene-level:
#                 No decorrelation and no biological annotations.
#
#              Only computes fdr.the (theoretical null), with no LASSO and no
#              covariate contribution analysis.
#
#              The SNP list and gene lists are retained from the original
#              analysis to ensure that sensitivity results are directly
#              comparable with the primary results.
#
# Usage:
#   Rscript fdrreg_sensitivity_analysis_rg.R \
#       --target scz2012 \
#       --traits_with adhd2019,alco2018,bd2018,ed2019,mdd2019,ocd2018 \
#       --traits_no asd2019,cannabis,dx.dep,ever.csh,ever.sh,ever.st,inte,life.threat.accident,mddco,neo.o,neuroti2018,no.dep,physical.crime,ptsd2019,sleep.dura,st.dep \
#       --lasso N \
#       --seed 100
#
# Date: 2026/07/05
# Author: Chief Scientist
# Version: 2.0
# Update: Reuses harmonised MAGMA input files produced by fdrreg.R v2.0.

#-----------------------------#
#---- Configuration Setup ----#
#-----------------------------#

rm(list = ls())

options(
  stringsAsFactors = FALSE,
  warn = 1
)

suppressPackageStartupMessages({
  library(optparse)
  library(data.table)
  library(FDRreg)
  library(stringr)
})

#-------------------------------#
#---- Command-Line Arguments ---#
#-------------------------------#

option_list <- list(
  make_option(
    "--target",
    type = "character",
    default = NULL,
    help = "Target disease name (required), e.g. scz2012"
  ),
  make_option(
    "--traits_with",
    type = "character",
    default = "",
    help = paste(
      "Comma-separated traits WITH sample overlap.",
      "Their z.decor values were decorrelated upstream by fdrreg.R."
    )
  ),
  make_option(
    "--traits_no",
    type = "character",
    default = "",
    help = paste(
      "Comma-separated traits WITHOUT sample overlap.",
      "Their z.decor values equal their harmonised signed z-scores."
    )
  ),
  make_option(
    "--lasso",
    type = "character",
    default = "N",
    help = "LASSO feature selection is ignored in this sensitivity analysis."
  ),
  make_option(
    "--seed",
    type = "integer",
    default = 100,
    help = "Random seed for reproducibility. Default: 100"
  )
)

opt <- parse_args(OptionParser(option_list = option_list))

if (is.null(opt$target)) {
  stop("Argument --target is required.")
}

#-------------------------------#
#---- General Helper Functions -#
#-------------------------------#

# Parse a comma-separated trait list.
parse_trait_list <- function(x) {
  if (is.null(x) || nchar(trimws(x)) == 0L) {
    return(character(0))
  }

  vals <- trimws(strsplit(x, ",", fixed = TRUE)[[1]])
  unique(vals[nchar(vals) > 0L])
}

# Convert a two-sided p-value to an unsigned z-score safely.
p_to_z_safe <- function(p, cap = 8.2) {
  p <- as.numeric(p)

  p_clamped <- pmax(
    pmin(p, 1 - .Machine$double.eps),
    .Machine$double.eps
  )

  z <- qnorm(1 - p_clamped / 2)
  pmin(pmax(z, 0), cap)
}

# Remove the Ensembl version suffix.
strip_gene_version <- function(gene_ids) {
  sub("\\..*$", "", as.character(gene_ids))
}

# Align a data.table to a reference key vector.
#
# This function uses explicit key matching rather than relying on row sorting.
# It stops if any reference identifier is missing or duplicated.
align_to_reference <- function(dt, key_col, reference_keys, data_label) {
  if (!key_col %in% names(dt)) {
    stop(sprintf(
      "Required key column '%s' is missing from %s.",
      key_col,
      data_label
    ))
  }

  data_keys <- as.character(dt[[key_col]])
  reference_keys <- as.character(reference_keys)

  duplicated_data_keys <- unique(data_keys[duplicated(data_keys)])
  if (length(duplicated_data_keys) > 0L) {
    stop(sprintf(
      "%s contains duplicated values in '%s'. Examples: %s",
      data_label,
      key_col,
      paste(head(duplicated_data_keys, 10), collapse = ", ")
    ))
  }

  duplicated_reference_keys <- unique(
    reference_keys[duplicated(reference_keys)]
  )
  if (length(duplicated_reference_keys) > 0L) {
    stop(sprintf(
      "The reference list contains duplicated identifiers. Examples: %s",
      paste(head(duplicated_reference_keys, 10), collapse = ", ")
    ))
  }

  idx <- match(reference_keys, data_keys)

  if (anyNA(idx)) {
    missing_keys <- reference_keys[is.na(idx)]

    stop(sprintf(
      paste0(
        "%s does not contain all identifiers from the original reference list. ",
        "Missing: %d. Examples: %s"
      ),
      data_label,
      length(missing_keys),
      paste(head(missing_keys, 10), collapse = ", ")
    ))
  }

  aligned_dt <- dt[idx]

  if (!identical(
    as.character(aligned_dt[[key_col]]),
    reference_keys
  )) {
    stop("Internal alignment failure for ", data_label)
  }

  aligned_dt
}

# Validate a numeric vector before FDRreg.
validate_numeric_vector <- function(x, label) {
  if (!is.numeric(x)) {
    x <- suppressWarnings(as.numeric(x))
  }

  if (length(x) == 0L) {
    stop(label, " is empty.")
  }

  bad <- !is.finite(x)
  if (any(bad)) {
    stop(sprintf(
      "%s contains %d non-finite values.",
      label,
      sum(bad)
    ))
  }

  x
}

#-------------------------------#
#---- Parsed Configuration -----#
#-------------------------------#

target_name <- trimws(opt$target)
traits_with <- parse_trait_list(opt$traits_with)
traits_no <- parse_trait_list(opt$traits_no)
all_traits <- c(traits_with, traits_no)
random_seed <- opt$seed

if (length(all_traits) == 0L) {
  stop("At least one trait must be specified via --traits_with or --traits_no.")
}

if (target_name %in% all_traits) {
  stop("The target trait must not also be included as a covariate trait.")
}

duplicated_across_groups <- intersect(traits_with, traits_no)
if (length(duplicated_across_groups) > 0L) {
  stop(
    "Traits cannot occur in both --traits_with and --traits_no: ",
    paste(duplicated_across_groups, collapse = ", ")
  )
}

set.seed(random_seed)
start_time <- Sys.time()

cat("============================================================\n")
cat("Comprehensive Sensitivity Analysis Configuration:\n")
cat("  Target:                     ", target_name, "\n")
cat(
  "  Traits with sample overlap: ",
  ifelse(
    length(traits_with) == 0L,
    "(none)",
    paste(traits_with, collapse = ", ")
  ),
  "\n"
)
cat(
  "  Traits without overlap:     ",
  ifelse(
    length(traits_no) == 0L,
    "(none)",
    paste(traits_no, collapse = ", ")
  ),
  "\n"
)
cat("  Total traits:               ", length(all_traits), "\n")
cat("  Random seed:                ", random_seed, "\n")
cat("  SNP source:                  fdrreg.R MAGMA input z.decor\n")
cat("============================================================\n")

#-------------------------------#
#---- Fixed Path Parameters ----#
#-------------------------------#

base_output_path <- "/exeh_4/jinghong_qiu/SO_Lab/18.fdrreg_rebuild"

sensitivity_output_path <- file.path(
  base_output_path,
  "01.extra.analysis",
  "06.rg"
)

target_output_dir <- file.path(
  sensitivity_output_path,
  target_name
)

dir.create(
  target_output_dir,
  showWarnings = FALSE,
  recursive = TRUE
)

# MAGMA input files generated by Phase 4 of fdrreg.R.
magma_input_dir <- file.path(
  base_output_path,
  target_name,
  "01.magma_input"
)

sig_threshold <- 0.01

# Initialize summary variables so the final table can always be generated.
snp_fdr_n_sig <- NA_integer_
snp_total <- NA_integer_
snp_qval_n_sig <- NA_integer_
snp_qval_total <- NA_integer_

magma_fdr_n_sig <- NA_integer_
magma_total <- NA_integer_
magma_qval_n_sig <- NA_integer_
magma_qval_total <- NA_integer_

smultixcan_fdr_n_sig <- NA_integer_
smultixcan_total <- NA_integer_
smultixcan_qval_n_sig <- NA_integer_
smultixcan_qval_total <- NA_integer_

overlapping_snps <- character(0)
has_overlap <- length(traits_with) > 0L

#=============================================================#
#---- PART 1: SNP SENSITIVITY USING MAGMA INPUT FILES --------#
#=============================================================#

cat("\n============================================================\n")
cat("PART 1: SNP Sensitivity Analysis\n")
cat("============================================================\n")

# The files generated by fdrreg.R contain:
#
# target:
#   z.decor = decorrelated target z when sample-overlapping traits exist,
#             otherwise original target z.
#
# traits_with:
#   z.decor = harmonised and decorrelated trait z.
#
# traits_no:
#   z.decor = harmonised trait z without decorrelation.
#
# Therefore, reusing z.decor exactly reproduces the original SNP background,
# harmonisation convention, and decorrelation state.

if (!dir.exists(magma_input_dir)) {
  stop(
    "MAGMA input directory not found: ",
    magma_input_dir,
    "\nRun fdrreg.R for this target first."
  )
}

get_magma_input_file <- function(trait_name) {
  file.path(
    magma_input_dir,
    paste0(trait_name, ".overlap.4magma.txt")
  )
}

read_magma_z <- function(trait_name) {
  input_file <- get_magma_input_file(trait_name)

  if (!file.exists(input_file)) {
    stop(
      "MAGMA input file not found for trait '",
      trait_name,
      "': ",
      input_file
    )
  }

  header <- names(fread(input_file, nrows = 0L))
  required_columns <- c("snpid", "z.decor")
  missing_columns <- setdiff(required_columns, header)

  if (length(missing_columns) > 0L) {
    stop(
      "Required columns missing from ",
      input_file,
      ": ",
      paste(missing_columns, collapse = ", ")
    )
  }

  dt <- fread(
    input_file,
    select = required_columns
  )

  if (nrow(dt) == 0L) {
    stop("MAGMA input file is empty: ", input_file)
  }

  dt[, snpid := as.character(snpid)]

  if (anyNA(dt$snpid) || any(dt$snpid == "")) {
    stop("Missing or empty snpid values found in: ", input_file)
  }

  if (anyDuplicated(dt$snpid)) {
    duplicated_ids <- unique(dt$snpid[duplicated(dt$snpid)])

    stop(
      "Duplicated snpid values found in ",
      input_file,
      ". Examples: ",
      paste(head(duplicated_ids, 10), collapse = ", ")
    )
  }

  dt[, z.decor := validate_numeric_vector(
    z.decor,
    paste0("z.decor for ", trait_name)
  )]

  dt
}

# ---- Load target MAGMA input ---- #

cat("Loading target MAGMA input...\n")

target_snp_data <- read_magma_z(target_name)
overlapping_snps <- target_snp_data$snpid
target_z_snp <- target_snp_data[["z.decor"]]

cat(sprintf(
  "Loaded target MAGMA input: %d SNPs\n",
  length(overlapping_snps)
))

# ---- Check and load all trait MAGMA inputs ---- #

trait_input_files <- vapply(
  all_traits,
  get_magma_input_file,
  character(1)
)

missing_trait_files <- all_traits[!file.exists(trait_input_files)]

if (length(missing_trait_files) > 0L) {
  stop(
    "MAGMA input files are missing for the following traits: ",
    paste(missing_trait_files, collapse = ", "),
    "\nThe sensitivity analysis requires the files generated by fdrreg.R."
  )
}

cat("Loading harmonised/decorrelated trait z.decor values...\n")

trait_snp_data <- setNames(
  vector("list", length(all_traits)),
  all_traits
)

for (trait in all_traits) {
  trait_dt <- read_magma_z(trait)

  trait_dt <- align_to_reference(
    dt = trait_dt,
    key_col = "snpid",
    reference_keys = overlapping_snps,
    data_label = paste0("SNP MAGMA input for ", trait)
  )

  trait_snp_data[[trait]] <- trait_dt

  cat(sprintf(
    "  Loaded and aligned: %-22s %d SNPs\n",
    trait,
    nrow(trait_dt)
  ))
}

if (has_overlap) {
  cat(sprintf(
    paste0(
      "Using upstream decorrelated z.decor values for ",
      "%d sample-overlapping traits.\n"
    ),
    length(traits_with)
  ))
} else {
  cat("No sample-overlapping traits were specified.\n")
}

# ---- Build SNP feature matrix ---- #

cat("\nBuilding SNP feature matrix from abs(z.decor)...\n")

feature_matrix_snp <- do.call(
  cbind,
  lapply(
    all_traits,
    function(trait) {
      abs(trait_snp_data[[trait]][["z.decor"]])
    }
  )
)

if (is.null(dim(feature_matrix_snp))) {
  feature_matrix_snp <- matrix(
    feature_matrix_snp,
    ncol = 1L
  )
}

colnames(feature_matrix_snp) <- all_traits
storage.mode(feature_matrix_snp) <- "double"

if (nrow(feature_matrix_snp) != length(target_z_snp)) {
  stop(
    "SNP feature matrix row count does not match target z-score length."
  )
}

if (any(!is.finite(feature_matrix_snp))) {
  stop("The SNP feature matrix contains non-finite values.")
}

cat(sprintf(
  "SNP feature matrix: %d x %d\n",
  nrow(feature_matrix_snp),
  ncol(feature_matrix_snp)
))

# ---- Run SNP-level FDRreg ---- #

cat("Running FDRreg (theoretical null) for SNP...\n")

set.seed(random_seed)

fdr_snp_theoretical <- FDRreg(
  target_z_snp,
  feature_matrix_snp,
  nulltype = "theoretical",
  method = "pr"
)

fdr_snp <- fdr_snp_theoretical$FDR
snp_fdr_n_sig <- sum(fdr_snp < sig_threshold, na.rm = TRUE)
snp_total <- length(fdr_snp)

cat(sprintf(
  "SNP fdr.the < %.2f: %d / %d\n",
  sig_threshold,
  snp_fdr_n_sig,
  snp_total
))

# ---- Load original SNP q-value results ---- #

cat("Loading original SNP q-value statistics...\n")

original_snp_fdr_file <- file.path(
  base_output_path,
  target_name,
  "02.fdrreg_results",
  "fdr_values_per_snp_nolasso.csv"
)

if (file.exists(original_snp_fdr_file)) {
  original_snp_results <- fread(original_snp_fdr_file)

  if ("qval_bh" %in% names(original_snp_results)) {
    snp_qval_n_sig <- sum(
      original_snp_results$qval_bh < sig_threshold,
      na.rm = TRUE
    )
    snp_qval_total <- nrow(original_snp_results)

    cat(sprintf(
      "Original SNP qval < %.2f: %d / %d\n",
      sig_threshold,
      snp_qval_n_sig,
      snp_qval_total
    ))

    if ("snpid" %in% names(original_snp_results)) {
      original_snp_ids <- as.character(original_snp_results$snpid)

      if (!identical(original_snp_ids, overlapping_snps)) {
        warning(
          paste0(
            "The SNP order in the original FDRreg result does not exactly ",
            "match the target MAGMA input. The current sensitivity output ",
            "uses the target MAGMA input order."
          )
        )
      }
    }
  } else {
    warning("qval_bh column not found in original SNP results.")
  }
} else {
  warning(
    "Original SNP FDR result file not found: ",
    original_snp_fdr_file
  )
}

# ---- Save SNP results ---- #

snp_results_dt <- data.table(
  snpid = overlapping_snps,
  z_score_signed = target_z_snp,
  fdr_the = fdr_snp
)

fwrite(
  snp_results_dt,
  file.path(
    target_output_dir,
    paste0(target_name, "_snp_fdr_the.csv")
  )
)

# Free large SNP objects before gene-level analyses.
rm(
  target_snp_data,
  trait_snp_data,
  feature_matrix_snp,
  fdr_snp_theoretical
)
gc()

#=============================================================#
#---- PART 2: MAGMA SENSITIVITY ANALYSIS ---------------------#
#=============================================================#

cat("\n============================================================\n")
cat("PART 2: MAGMA Sensitivity Analysis\n")
cat("============================================================\n")

magma_output_dir <- file.path(
  base_output_path,
  target_name,
  "04.magma_output"
)

magma_fdrreg_dir <- file.path(
  base_output_path,
  target_name,
  "05.magma_fdrreg"
)

# ---- MAGMA helper functions ---- #

# Detect the MAGMA gene identifier column.
# MAGMA .genes.out usually uses GENE, while some downstream FDRreg files use ID.
detect_magma_gene_column <- function(dt, data_label) {
  candidates <- c("GENE", "ID")
  matched <- candidates[candidates %in% names(dt)]

  if (length(matched) == 0L) {
    stop(
      "No MAGMA gene identifier column was found in ",
      data_label,
      ". Expected one of: ",
      paste(candidates, collapse = ", "),
      ". Available columns: ",
      paste(names(dt), collapse = ", ")
    )
  }

  matched[1]
}

# Detect the MAGMA p-value column.
detect_magma_p_column <- function(dt, data_label) {
  candidates <- c("P", "p", "pvalue", "PVAL", "pval")
  matched <- candidates[candidates %in% names(dt)]

  if (length(matched) == 0L) {
    stop(
      "No p-value column was found in ",
      data_label,
      ". Expected one of: ",
      paste(candidates, collapse = ", "),
      ". Available columns: ",
      paste(names(dt), collapse = ", ")
    )
  }

  matched[1]
}

# Add a standardized character gene identifier column.
standardize_magma_gene_id <- function(dt, data_label) {
  gene_col <- detect_magma_gene_column(dt, data_label)

  dt[, GENE_KEY := trimws(as.character(get(gene_col)))]

  if (anyNA(dt$GENE_KEY) || any(dt$GENE_KEY == "")) {
    stop(
      "Missing or empty MAGMA gene identifiers found in ",
      data_label,
      "."
    )
  }

  duplicated_ids <- unique(dt$GENE_KEY[duplicated(dt$GENE_KEY)])

  if (length(duplicated_ids) > 0L) {
    stop(
      "Duplicated MAGMA gene identifiers found in ",
      data_label,
      ". Examples: ",
      paste(head(duplicated_ids, 10), collapse = ", ")
    )
  }

  attr(dt, "original_gene_column") <- gene_col
  dt
}

# ---- Load original MAGMA FDRreg results ---- #

cat("Loading original MAGMA results and reference gene list...\n")

original_magma_gene_list <- NULL

original_magma_file <- file.path(
  magma_fdrreg_dir,
  paste0(target_name, ".gene.bio.fdrreg.txt")
)

if (file.exists(original_magma_file)) {
  original_magma_results <- fread(original_magma_file)

  original_magma_results <- standardize_magma_gene_id(
    original_magma_results,
    paste0("original MAGMA FDRreg results: ", original_magma_file)
  )

  # Preserve the exact gene list and order used by the original analysis.
  original_magma_gene_list <- original_magma_results$GENE_KEY

  magma_qval_total <- nrow(original_magma_results)

  if ("qval" %in% names(original_magma_results)) {
    magma_qval_n_sig <- sum(
      original_magma_results$qval < sig_threshold,
      na.rm = TRUE
    )
  } else {
    magma_qval_n_sig <- NA_integer_
    warning(
      "qval column not found in original MAGMA results: ",
      original_magma_file
    )
  }

  original_gene_column <- attr(
    original_magma_results,
    "original_gene_column"
  )

  cat(sprintf(
    "Original MAGMA gene identifier column: %s\n",
    original_gene_column
  ))
  cat(sprintf(
    "Original MAGMA genes: %d\n",
    magma_qval_total
  ))
  cat(sprintf(
    "Original MAGMA qval < %.2f: %s / %d\n",
    sig_threshold,
    ifelse(
      is.na(magma_qval_n_sig),
      "NA",
      as.character(magma_qval_n_sig)
    ),
    magma_qval_total
  ))
} else {
  warning(
    "Original MAGMA results file not found: ",
    original_magma_file,
    "\nA common gene list will be constructed as a fallback."
  )
}

# ---- Load target MAGMA gene output ---- #

cat("\nLoading MAGMA gene output files...\n")

target_magma_file <- file.path(
  magma_output_dir,
  paste0(target_name, ".genes.out")
)

if (!file.exists(target_magma_file)) {
  warning("Target MAGMA file not found: ", target_magma_file)
} else {
  target_magma <- fread(target_magma_file)

  target_magma <- standardize_magma_gene_id(
    target_magma,
    paste0("target MAGMA output: ", target_magma_file)
  )

  target_p_column <- detect_magma_p_column(
    target_magma,
    paste0("target MAGMA output: ", target_magma_file)
  )

  # Store the p-value in a standardized column.
  target_magma[, P_VALUE := suppressWarnings(
    as.numeric(get(target_p_column))
  )]

  if (any(!is.finite(target_magma$P_VALUE))) {
    stop(
      "Non-finite MAGMA p-values found in target file: ",
      target_magma_file
    )
  }

  if (any(target_magma$P_VALUE < 0 | target_magma$P_VALUE > 1)) {
    stop(
      "MAGMA p-values outside [0, 1] found in target file: ",
      target_magma_file
    )
  }

  target_gene_column <- attr(
    target_magma,
    "original_gene_column"
  )

  cat(sprintf(
    "  Loaded target MAGMA: %s; gene column = %s; p-value column = %s\n",
    target_name,
    target_gene_column,
    target_p_column
  ))

  # ---- Load trait MAGMA outputs ---- #

  trait_magma_data <- list()
  valid_magma_traits <- character(0)

  for (trait in all_traits) {
    trait_file <- file.path(
      magma_output_dir,
      paste0(trait, ".genes.out")
    )

    if (!file.exists(trait_file)) {
      warning(sprintf(
        "  MAGMA file not found: %s",
        trait_file
      ))
      next
    }

    dt <- fread(trait_file)

    # Detect and standardize the gene identifier.
    gene_detection <- tryCatch(
      {
        dt <- standardize_magma_gene_id(
          dt,
          paste0("MAGMA output for ", trait, ": ", trait_file)
        )
        TRUE
      },
      error = function(e) {
        warning(conditionMessage(e))
        FALSE
      }
    )

    if (!gene_detection) {
      next
    }

    # Detect and standardize the p-value.
    p_column <- tryCatch(
      detect_magma_p_column(
        dt,
        paste0("MAGMA output for ", trait, ": ", trait_file)
      ),
      error = function(e) {
        warning(conditionMessage(e))
        NULL
      }
    )

    if (is.null(p_column)) {
      next
    }

    dt[, P_VALUE := suppressWarnings(
      as.numeric(get(p_column))
    )]

    if (any(!is.finite(dt$P_VALUE))) {
      warning(sprintf(
        "Skipping MAGMA trait '%s': non-finite p-values were found.",
        trait
      ))
      next
    }

    if (any(dt$P_VALUE < 0 | dt$P_VALUE > 1)) {
      warning(sprintf(
        "Skipping MAGMA trait '%s': p-values outside [0, 1] were found.",
        trait
      ))
      next
    }

    trait_magma_data[[trait]] <- dt
    valid_magma_traits <- c(
      valid_magma_traits,
      trait
    )

    cat(sprintf(
      "  Loaded MAGMA: %-22s gene column = %s; p-value column = %s\n",
      trait,
      attr(dt, "original_gene_column"),
      p_column
    ))
  }

  if (length(valid_magma_traits) == 0L) {
    warning("No valid MAGMA trait files found.")
  } else {
    # ---- Define the reference gene list ---- #

    if (!is.null(original_magma_gene_list)) {
      # This is the preferred branch because it guarantees that the
      # sensitivity analysis uses the exact original gene list and order.
      reference_magma_genes <- original_magma_gene_list

      cat(sprintf(
        "Using exact original MAGMA gene list and order: %d genes\n",
        length(reference_magma_genes)
      ))
    } else {
      # Fallback only when the original FDRreg result is unavailable.
      reference_magma_genes <- Reduce(
        intersect,
        c(
          list(target_magma$GENE_KEY),
          lapply(
            trait_magma_data[valid_magma_traits],
            `[[`,
            "GENE_KEY"
          )
        )
      )

      reference_magma_genes <- sort(
        unique(reference_magma_genes)
      )

      cat(sprintf(
        "Using fallback common MAGMA gene list: %d genes\n",
        length(reference_magma_genes)
      ))
    }

    if (length(reference_magma_genes) == 0L) {
      warning("No common MAGMA genes found.")
    } else {
      # ---- Align target to the original gene list ---- #

      target_magma <- align_to_reference(
        dt = target_magma,
        key_col = "GENE_KEY",
        reference_keys = reference_magma_genes,
        data_label = paste0(
          "target MAGMA output for ",
          target_name
        )
      )

      # ---- Align each trait to the same gene list and order ---- #

      aligned_trait_magma_data <- setNames(
        vector("list", length(valid_magma_traits)),
        valid_magma_traits
      )

      for (trait in valid_magma_traits) {
        aligned_trait_magma_data[[trait]] <- align_to_reference(
          dt = trait_magma_data[[trait]],
          key_col = "GENE_KEY",
          reference_keys = reference_magma_genes,
          data_label = paste0(
            "MAGMA output for ",
            trait
          )
        )
      }

      trait_magma_data <- aligned_trait_magma_data

      # Final alignment checks.
      if (!identical(
        target_magma$GENE_KEY,
        reference_magma_genes
      )) {
        stop(
          "Target MAGMA gene order does not match the reference gene list."
        )
      }

      alignment_ok <- vapply(
        trait_magma_data,
        function(dt) {
          identical(
            dt$GENE_KEY,
            reference_magma_genes
          )
        },
        logical(1)
      )

      if (!all(alignment_ok)) {
        stop(
          "MAGMA gene alignment failed for: ",
          paste(
            names(alignment_ok)[!alignment_ok],
            collapse = ", "
          )
        )
      }

      # ---- Build MAGMA feature matrix ---- #

      feature_matrix_magma <- do.call(
        cbind,
        lapply(
          trait_magma_data,
          function(dt) {
            p_to_z_safe(dt$P_VALUE)
          }
        )
      )

      # Preserve matrix structure when there is only one trait.
      if (is.null(dim(feature_matrix_magma))) {
        feature_matrix_magma <- matrix(
          feature_matrix_magma,
          ncol = 1L
        )
      }

      colnames(feature_matrix_magma) <- valid_magma_traits
      storage.mode(feature_matrix_magma) <- "double"

      if (nrow(feature_matrix_magma) != nrow(target_magma)) {
        stop(
          "MAGMA feature matrix row count does not match target gene count."
        )
      }

      if (any(!is.finite(feature_matrix_magma))) {
        stop(
          "The MAGMA feature matrix contains non-finite values."
        )
      }

      # ---- Build signed target z-scores ---- #
      #
      # MAGMA gene-level output only provides unsigned p-values.
      # Random signs are assigned using the specified seed, matching the
      # original sensitivity analysis.

      target_z_magma_unsigned <- p_to_z_safe(
        target_magma$P_VALUE
      )

      set.seed(random_seed)

      target_z_magma <- target_z_magma_unsigned *
        sign(rnorm(length(target_z_magma_unsigned)))

      if (any(!is.finite(target_z_magma))) {
        stop(
          "The target MAGMA z-score vector contains non-finite values."
        )
      }

      cat(sprintf(
        "MAGMA feature matrix: %d x %d\n",
        nrow(feature_matrix_magma),
        ncol(feature_matrix_magma)
      ))

      # ---- Run MAGMA-level FDRreg ---- #

      cat("Running FDRreg (theoretical null) for MAGMA...\n")

      fdr_magma_theoretical <- FDRreg(
        target_z_magma,
        feature_matrix_magma,
        nulltype = "theoretical",
        method = "pr"
      )

      fdr_magma <- fdr_magma_theoretical$FDR

      magma_fdr_n_sig <- sum(
        fdr_magma < sig_threshold,
        na.rm = TRUE
      )

      magma_total <- length(fdr_magma)

      cat(sprintf(
        "MAGMA fdr.the < %.2f: %d / %d\n",
        sig_threshold,
        magma_fdr_n_sig,
        magma_total
      ))

      # ---- Save MAGMA results ---- #
      #
      # Use the standardized MAGMA gene identifier. For your current data,
      # this will contain the values from ID in the original FDRreg file and
      # GENE in the .genes.out files.

      magma_results_dt <- data.table(
        GENE = target_magma$GENE_KEY,
        target_z = target_z_magma,
        fdr_the = fdr_magma
      )

      magma_output_file <- file.path(
        target_output_dir,
        paste0(
          target_name,
          "_magma_fdr_the.csv"
        )
      )

      fwrite(
        magma_results_dt,
        magma_output_file
      )

      cat(sprintf(
        "Written MAGMA sensitivity results: %s\n",
        magma_output_file
      ))
    }
  }
}

#=============================================================#
#---- PART 3: SmultiXcan SENSITIVITY ANALYSIS ----------------#
#=============================================================#

cat("\n============================================================\n")
cat("PART 3: SmultiXcan Sensitivity Analysis\n")
cat("============================================================\n")

smultixcan_output_dir <- file.path(
  base_output_path,
  target_name,
  "08.smultixcan_output"
)

smultixcan_fdrreg_dir <- file.path(
  base_output_path,
  target_name,
  "09.smultixcan_fdrreg"
)

# ---- Load original SmultiXcan results ---- #

cat("Loading original SmultiXcan results and reference gene list...\n")

original_smultixcan_gene_list <- NULL

original_smultixcan_file <- file.path(
  smultixcan_fdrreg_dir,
  paste0(target_name, ".gene.bio.fdrreg.txt")
)

if (file.exists(original_smultixcan_file)) {
  original_smultixcan_results <- fread(original_smultixcan_file)

  if (!"ENSEMBL_GENE_ID" %in% names(original_smultixcan_results)) {
    stop(
      "ENSEMBL_GENE_ID column is missing from: ",
      original_smultixcan_file
    )
  }

  original_smultixcan_gene_list <- strip_gene_version(
    original_smultixcan_results$ENSEMBL_GENE_ID
  )

  if (anyDuplicated(original_smultixcan_gene_list)) {
    stop(
      paste0(
        "Duplicated ENSEMBL_GENE_ID values found in the original ",
        "SmultiXcan reference results after version stripping."
      )
    )
  }

  smultixcan_qval_total <- nrow(original_smultixcan_results)

  if ("qval" %in% names(original_smultixcan_results)) {
    smultixcan_qval_n_sig <- sum(
      original_smultixcan_results$qval < sig_threshold,
      na.rm = TRUE
    )
  } else {
    warning("qval column not found in original SmultiXcan results.")
  }

  cat(sprintf(
    "Original SmultiXcan genes: %d\n",
    smultixcan_qval_total
  ))
  cat(sprintf(
    "Original SmultiXcan qval < %.2f: %s / %d\n",
    sig_threshold,
    ifelse(
      is.na(smultixcan_qval_n_sig),
      "NA",
      smultixcan_qval_n_sig
    ),
    smultixcan_qval_total
  ))
} else {
  warning(
    "Original SmultiXcan results file not found: ",
    original_smultixcan_file,
    "\nA common gene list will be constructed as a fallback."
  )
}

# ---- Load target SmultiXcan output ---- #

cat("\nLoading SmultiXcan gene output files...\n")

target_smultixcan_file <- file.path(
  smultixcan_output_dir,
  paste0(target_name, ".allbrain.txt")
)

if (!file.exists(target_smultixcan_file)) {
  warning(
    "Target SmultiXcan file not found: ",
    target_smultixcan_file
  )
} else {
  target_header <- names(
    fread(target_smultixcan_file, nrows = 0L)
  )

  target_columns <- c("gene", "gene_name", "pvalue")
  missing_target_columns <- setdiff(
    target_columns,
    target_header
  )

  if (length(missing_target_columns) > 0L) {
    stop(
      "Required columns missing from target SmultiXcan file: ",
      paste(missing_target_columns, collapse = ", ")
    )
  }

  target_smultixcan <- fread(
    target_smultixcan_file,
    select = target_columns
  )

  target_smultixcan[, gene_stripped := strip_gene_version(gene)]

  # ---- Load trait SmultiXcan outputs ---- #

  trait_smultixcan_data <- list()
  valid_smultixcan_traits <- character(0)

  for (trait in all_traits) {
    trait_file <- file.path(
      smultixcan_output_dir,
      paste0(trait, ".allbrain.txt")
    )

    if (!file.exists(trait_file)) {
      warning(sprintf(
        "  SmultiXcan file not found: %s",
        trait_file
      ))
      next
    }

    trait_header <- names(fread(trait_file, nrows = 0L))
    required_columns <- c("gene", "pvalue")
    missing_columns <- setdiff(
      required_columns,
      trait_header
    )

    if (length(missing_columns) > 0L) {
      warning(sprintf(
        "Skipping SmultiXcan trait '%s'; missing columns: %s",
        trait,
        paste(missing_columns, collapse = ", ")
      ))
      next
    }

    dt <- fread(
      trait_file,
      select = required_columns
    )

    dt[, gene_stripped := strip_gene_version(gene)]

    trait_smultixcan_data[[trait]] <- dt
    valid_smultixcan_traits <- c(
      valid_smultixcan_traits,
      trait
    )

    cat(sprintf(
      "  Loaded SmultiXcan: %s\n",
      trait
    ))
  }

  if (length(valid_smultixcan_traits) == 0L) {
    warning("No valid SmultiXcan trait files found.")
  } else {
    # Use the original gene list when available.
    if (!is.null(original_smultixcan_gene_list)) {
      reference_smultixcan_genes <- original_smultixcan_gene_list

      cat(sprintf(
        "Using original SmultiXcan gene list: %d genes\n",
        length(reference_smultixcan_genes)
      ))
    } else {
      reference_smultixcan_genes <- Reduce(
        intersect,
        c(
          list(target_smultixcan$gene_stripped),
          lapply(
            trait_smultixcan_data[valid_smultixcan_traits],
            `[[`,
            "gene_stripped"
          )
        )
      )

      reference_smultixcan_genes <- sort(
        unique(reference_smultixcan_genes)
      )

      cat(sprintf(
        "Using fallback common SmultiXcan gene list: %d genes\n",
        length(reference_smultixcan_genes)
      ))
    }

    if (length(reference_smultixcan_genes) == 0L) {
      warning("No common SmultiXcan genes found.")
    } else {
      target_smultixcan <- align_to_reference(
        dt = target_smultixcan,
        key_col = "gene_stripped",
        reference_keys = reference_smultixcan_genes,
        data_label = paste0(
          "Target SmultiXcan output for ",
          target_name
        )
      )

      trait_smultixcan_data <- lapply(
        valid_smultixcan_traits,
        function(trait) {
          align_to_reference(
            dt = trait_smultixcan_data[[trait]],
            key_col = "gene_stripped",
            reference_keys = reference_smultixcan_genes,
            data_label = paste0(
              "SmultiXcan output for ",
              trait
            )
          )
        }
      )

      names(trait_smultixcan_data) <- valid_smultixcan_traits

      # Build feature matrix from unsigned p-value-derived z-scores.
      feature_matrix_smultixcan <- do.call(
        cbind,
        lapply(
          trait_smultixcan_data,
          function(dt) {
            p_to_z_safe(dt$pvalue)
          }
        )
      )

      if (is.null(dim(feature_matrix_smultixcan))) {
        feature_matrix_smultixcan <- matrix(
          feature_matrix_smultixcan,
          ncol = 1L
        )
      }

      colnames(feature_matrix_smultixcan) <- valid_smultixcan_traits
      storage.mode(feature_matrix_smultixcan) <- "double"

      # Assign random signs to the target, matching the original code.
      target_z_smultixcan_unsigned <- p_to_z_safe(
        target_smultixcan$pvalue
      )

      set.seed(random_seed)

      target_z_smultixcan <- target_z_smultixcan_unsigned *
        sign(rnorm(length(target_z_smultixcan_unsigned)))

      cat(sprintf(
        "SmultiXcan feature matrix: %d x %d\n",
        nrow(feature_matrix_smultixcan),
        ncol(feature_matrix_smultixcan)
      ))

      cat("Running FDRreg (theoretical null) for SmultiXcan...\n")

      fdr_smultixcan_theoretical <- FDRreg(
        target_z_smultixcan,
        feature_matrix_smultixcan,
        nulltype = "theoretical",
        method = "pr"
      )

      fdr_smultixcan <- fdr_smultixcan_theoretical$FDR

      smultixcan_fdr_n_sig <- sum(
        fdr_smultixcan < sig_threshold,
        na.rm = TRUE
      )

      smultixcan_total <- length(fdr_smultixcan)

      cat(sprintf(
        "SmultiXcan fdr.the < %.2f: %d / %d\n",
        sig_threshold,
        smultixcan_fdr_n_sig,
        smultixcan_total
      ))

      smultixcan_results_dt <- data.table(
        ENSEMBL_GENE_ID = target_smultixcan$gene_stripped,
        fdr_the = fdr_smultixcan
      )

      fwrite(
        smultixcan_results_dt,
        file.path(
          target_output_dir,
          paste0(
            target_name,
            "_smultixcan_fdr_the.csv"
          )
        )
      )
    }
  }
}

#=============================================================#
#---- Combined Summary Table ---------------------------------#
#=============================================================#

cat("\n============================================================\n")
cat("Creating Combined Summary Table\n")
cat("============================================================\n")

safe_ratio <- function(numerator, denominator) {
  if (
    is.na(numerator) ||
    is.na(denominator) ||
    denominator <= 0
  ) {
    return(NA_real_)
  }

  numerator / denominator
}

combined_summary <- data.frame(
  analysis = c(
    "snp",
    "magma",
    "smultixcan"
  ),
  fdr_the_n_sig = c(
    snp_fdr_n_sig,
    magma_fdr_n_sig,
    smultixcan_fdr_n_sig
  ),
  fdr_the_total = c(
    snp_total,
    magma_total,
    smultixcan_total
  ),
  qval_n_sig = c(
    snp_qval_n_sig,
    magma_qval_n_sig,
    smultixcan_qval_n_sig
  ),
  qval_total = c(
    snp_qval_total,
    magma_qval_total,
    smultixcan_qval_total
  ),
  sensitivity_ratio = c(
    safe_ratio(
      snp_fdr_n_sig,
      snp_qval_n_sig
    ),
    safe_ratio(
      magma_fdr_n_sig,
      magma_qval_n_sig
    ),
    safe_ratio(
      smultixcan_fdr_n_sig,
      smultixcan_qval_n_sig
    )
  ),
  stringsAsFactors = FALSE
)

cat("\n---------- Combined Sensitivity Analysis Summary ----------\n")
cat(sprintf("Target: %s\n", target_name))
cat(sprintf(
  "Traits with sample overlap: %d (%s)\n",
  length(traits_with),
  ifelse(
    length(traits_with) == 0L,
    "none",
    paste(traits_with, collapse = ", ")
  )
))
cat(sprintf(
  "Traits without sample overlap: %d (%s)\n",
  length(traits_no),
  ifelse(
    length(traits_no) == 0L,
    "none",
    paste(traits_no, collapse = ", ")
  )
))
cat(sprintf("Seed: %d\n", random_seed))
cat(sprintf(
  "Significance threshold: %g\n\n",
  sig_threshold
))

print(combined_summary)

fwrite(
  combined_summary,
  file.path(
    target_output_dir,
    paste0(
      target_name,
      "_combined_sensitivity_summary.csv"
    )
  )
)

#-------------------------------#
#---- Save Analysis Config -----#
#-------------------------------#

config_info <- list(
  target = target_name,
  traits_with = traits_with,
  traits_no = traits_no,
  all_traits = all_traits,
  seed = random_seed,
  threshold = sig_threshold,
  has_snp_decorrelation = has_overlap,
  snp_source = "01.magma_input/*.overlap.4magma.txt",
  snp_z_column = "z.decor",
  snp_count = length(overlapping_snps),
  magma_gene_count = magma_total,
  smultixcan_gene_count = smultixcan_total,
  timestamp = Sys.time()
)

saveRDS(
  config_info,
  file.path(
    target_output_dir,
    paste0(
      target_name,
      "_sensitivity_config.rds"
    )
  )
)

#-------------------------------#
#---- Completion Summary -------#
#-------------------------------#

end_time <- Sys.time()

cat("\n============================================================\n")
cat("Sensitivity Analysis Complete!\n")
cat("============================================================\n")
cat(sprintf("Target: %s\n", target_name))
cat(sprintf(
  "Results saved to: %s\n",
  target_output_dir
))
cat(sprintf(
  "Time Start: %s\n",
  format(start_time, "%a %b %d %X %Y")
))
cat(sprintf(
  "Time End:   %s\n",
  format(end_time, "%a %b %d %X %Y")
))
cat(sprintf(
  "Duration:   %.2f seconds\n",
  as.numeric(
    difftime(
      end_time,
      start_time,
      units = "secs"
    )
  )
))
cat("============================================================\n")

q("no")
